AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  Process files as they are uploaded to an S3 bucket.

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'

  S3Lambda:
    Type: AWS::Serverless::Function
    Description: Process events from an S3 bucket.
    Properties:
      Runtime: python3.6
      Handler: s3_processor.lambda_handler
      CodeUri: ./src/s3_processor
      Tracing: Active
      Policies:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-bucket/*'
      Events:
        ObjectCreatedEvents:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'
