AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Send S3 Events to an SQS Queue for processing by a Lambda function.

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt S3Queue.Arn
    DependsOn:
      - S3QueuePolicy

  S3Queue:
    Type: AWS::SQS::Queue

  S3QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt S3Queue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:*:*:${AWS::StackName}-bucket'
      Queues:
        - !Ref S3Queue
    DependsOn:
    - S3Queue

  QueueProcessor:
    Type: AWS::Serverless::Function
    Description: Processes messages from the SQS Queue.
    Properties:
      CodeUri: ./src/queue_processor
      Handler: queue_processor.lambda_handler
      Runtime: python3.6
      Timeout: 30
      ReservedConcurrentExecutions: 10
      Events:
        QueueMessages:
          Type: SQS
          Properties:
            Queue: !GetAtt S3Queue.Arn
            BatchSize: 10